# Generated by Django 2.2.5 on 2019-09-29 10:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('receiver_address', models.TextField(blank=True, max_length=300, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('payment_address', models.TextField(blank=True, max_length=300, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('eu_country', models.BooleanField(default=False)),
                ('vat_number', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingname', models.CharField(max_length=300)),
                ('decimalvalue', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('textvalue', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('settingname',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('issued_date', models.DateField(default=datetime.date.today)),
                ('payment_term', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True, max_length=300, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('advance_required', models.BooleanField(default=False)),
                ('advance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_details', models.TextField(blank=True, max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Company')),
            ],
            options={
                'ordering': ('-issued_date',),
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=300, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('advance_required', models.BooleanField(default=False)),
                ('advance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Company')),
            ],
            options={
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.Template')),
            ],
            options={
                'ordering': ('order_number',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.Invoice')),
            ],
            options={
                'ordering': ('order_number',),
            },
        ),
    ]
