# Generated by Django 2.2.5 on 2019-11-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20191010_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_incoming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='invoices.Currency'),
        ),
        migrations.AlterField(
            model_name='bankrecord',
            name='deals',
            field=models.ManyToManyField(blank=True, related_name='bank_records', to='invoices.Deal'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bank_records',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='invoices.BankRecord'),
        ),
    ]
