# Generated by Django 2.2.5 on 2019-11-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20191111_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='invoices.Currency'),
        ),
    ]
