# Generated by Django 2.2.5 on 2019-11-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20191111_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='deal',
            name='name',
            field=models.CharField(default='N/A D', max_length=30),
        ),
    ]
