# Generated by Django 2.2.5 on 2019-11-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20191115_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ('-started_date', 'name')},
        ),
    ]
