# Generated by Django 2.2.5 on 2019-11-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20191115_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'default_permissions': ('view',), 'ordering': ('-issued_date',)},
        ),
    ]
