# Generated by Django 2.2.5 on 2019-11-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_bankaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='invoices.Department'),
        ),
    ]
