# Generated by Django 2.2.5 on 2019-11-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_auto_20191120_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrecord',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
