# Generated by Django 2.2.5 on 2019-11-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_auto_20191120_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrecord',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
