# Generated by Django 2.2.5 on 2019-11-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_auto_20191122_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name_plural': 'companies'},
        ),
    ]
