# Generated by Django 2.2.5 on 2019-11-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_auto_20191125_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
