# Generated by Django 2.2.5 on 2019-11-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_auto_20191125_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='department',
        ),
    ]
