# Generated by Django 2.2.5 on 2019-12-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_remove_company_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_not_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
