# Generated by Django 2.2.5 on 2019-12-04 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_invoice_total_not_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country_code',
            field=models.TextField(blank=True, max_length=3, validators=[django.core.validators.MaxLengthValidator(3)]),
        ),
    ]
