# Generated by Django 2.2.5 on 2019-12-04 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_company_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, validators=[django.core.validators.MaxLengthValidator(3)]),
        ),
    ]
