# Generated by Django 2.2.5 on 2020-02-25 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_auto_20191204_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='invoices.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='completed_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='deal',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='deal',
            name='total_invoiced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='deal',
            name='total_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
    ]
