# Generated by Django 2.2.5 on 2020-02-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_auto_20200225_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_invoiced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
