# Generated by Django 2.2.5 on 2020-02-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_auto_20200226_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ('-completed_date', '-started_date', 'name')},
        ),
    ]
