# Generated by Django 2.2.5 on 2020-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0028_auto_20200226_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file',
            field=models.FileField(default='', upload_to='invoice_files/'),
            preserve_default=False,
        ),
    ]
