# Generated by Django 2.2.5 on 2019-12-12 19:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=200, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QuoteIndication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_open', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('price_close', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('price_high', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('price_low', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('price_average', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indications', to='webparse.Symbol')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
