# Generated by Django 2.2.5 on 2019-12-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webparse', '0003_auto_20191214_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolcommodity',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
