# Generated by Django 2.2.5 on 2019-12-14 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webparse', '0004_auto_20191214_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolperiod',
            name='valid_till',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
